name: Release

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: docker.io
  USERNAME: ${{ github.actor }}
  IMAGE_NAME: rock5b-talos
  IMAGE_TAG: ${{ github.sha }}
  PLATFORM: linux/arm64
  PROGRESS: plain

jobs:
  release:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Build Flashable Image for Rock 5B
        run: |
          mkdir -p _out/
          make sbc-rock_5b

      - name: Tag Talos Docker Image
        run: |
          docker buildx imagetools create -t ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: _out/metal-rock_5b-arm64.img.xz
          generate_release_notes: true